# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-08-28 17:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Condidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(default=datetime.datetime(2018, 8, 28, 17, 58, 38, 783536, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(default=datetime.datetime(2018, 8, 28, 17, 58, 47, 39304, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
