# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-09-02 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Condidate', '0003_auto_20180828_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
