# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-08-28 18:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default=datetime.datetime(2018, 8, 28, 18, 7, 1, 642904, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default=datetime.datetime(2018, 8, 28, 18, 7, 7, 658187, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
    ]
